# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='name',
        ),
        migrations.AddField(
            model_name='inventory',
            name='vName',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='vName',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='qty',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(),
        ),
    ]
