# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApi', '0004_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='inventory',
        ),
        migrations.AddField(
            model_name='inventory',
            name='left',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventory',
            name='threshold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventory',
            name='unit',
            field=models.CharField(default='units', max_length=10),
        ),
        migrations.AlterField(
            model_name='entry',
            name='qty',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
