# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApi', '0005_auto_20171129_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='amount',
            field=models.FloatField(),
        ),
    ]
